version: 2.1

jobs:
  lint_code:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - lint-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Lint code
          command: make lint
      - save_cache:
          paths:
            - ./
          key: lint-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}

  containerize:
    docker:
      - image: circleci/python:3.7.3-stretch
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASS}
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build -t pgcorriente/udacity-devops-capstone-tmp:latest .
          docker tag pgcorriente/udacity-devops-capstone-tmp:latest pgcorriente/udacity-devops-capstone-tmp:${CIRCLE_WORKFLOW_ID:0:5}
          docker push pgcorriente/udacity-devops-capstone-tmp:latest
          docker push pgcorriente/udacity-devops-capstone-tmp:${CIRCLE_WORKFLOW_ID:0:5}

# TO DO:
# k8s_deploy
# test_cluster
# rollback if failure?
      
workflows:
  default:
    jobs:
      - lint_code
      - containerize:
          requires:
            - lint_code
