version: 2.1

commands:
  # From: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
  install_kubectl:
    description: Downloads kubectl for Linux and installs it on the AWS CLI container
    steps:
      - run:
          name: Download kubectl
          command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - run:
          name: Install kubectl
          command: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

jobs:
  build_image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys: [build-image}]
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Build image
          command: docker build -t pgcorriente/udacity-devops-capstone-tmp1 .
      - save_cache:
          paths: [./]
          key: build-image

  upload_image:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - install_kubectl
      - run:
          name: Test kubectl
          command: kubectl version --client
      # Rellenar
    
  create_kubernetes:
    docker:
      - image: amazon/aws-cli
    steps:
      # Rellenar

  deploy_container:
    docker:
      - image: amazon/aws-cli
    steps:
      # Se puede unir con el paso anterior?

  test_deployment:
    docker:
      - image: # Rellenar
    steps:
      # Rellenar
      # Es necesario un rollback si el test no funciona...
      
workflows:
  default:
    jobs:
      - build_image
      - upload_image:
          requires:
            - build_image
      - create_kubernetes
          requires:
            - upload_image
      - deploy_container
          requires:
            - build_image
            - upload_image
            - create_kubernetes
      - test_deployment
          requires:
            - build_image
            - upload_image
            - create_kubernetes
            - deploy_container
