version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.1

jobs:
  lint_code:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - lint-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Lint code
          command: make lint
      - save_cache:
          paths:
            - ./
          key: lint-{{ .Environment.CACHE_VERSION }}-{{ checksum "requirements.txt" }}

  containerize:
    docker:
      - image: circleci/python:3.7.3-stretch
        auth:
          username: ${DOCKER_USER}
          password: ${DOCKER_PASS}
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker build -t pgcorriente/udacity-devops-capstone-tmp:latest .
          docker tag pgcorriente/udacity-devops-capstone-tmp:latest pgcorriente/udacity-devops-capstone-tmp:${CIRCLE_WORKFLOW_ID:0:5}
          docker push pgcorriente/udacity-devops-capstone-tmp:latest
          docker push pgcorriente/udacity-devops-capstone-tmp:${CIRCLE_WORKFLOW_ID:0:5}

  k8s_deploy:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${CLUSTER_NAME}
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/${CLUSTER_NAME}

  test-deployment:
    executor: aws-eks/python3
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${CLUSTER_NAME}
      - run:
          name: Test cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
      
workflows:
  default:
    jobs:
      - lint_code
      - containerize:
          requires:
            - lint_code
      - k8s_deploy:
          requires:
            - lint_code
            - containerize
      - test-deployment:
          requires:
            - lint_code
            - containerize
            - k8s_deploy
